:concurrency: <%= Integer(ENV.fetch("SIDEKIQ_CONCURRENCY", 5)) %>
:queues:
  - imports
  - default
  - recurring

:scheduler:
  :schedule:
    materialize_recurring_transactions:
      cron: "0 4 * * * America/Sao_Paulo"
      class: "RecurringRules::MaterializeDueTransactionsJob"
      queue: recurring
